<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\OdinVault.Core\OdinVault.Core.csproj" />
    <ProjectReference Include="..\OdinVault.Persistence\OdinVault.Persistence.csproj" />
    <ProjectReference Include="..\OdinVault.Database.SqlServer\OdinVault.Database.SqlServer.csproj" />
    <ProjectReference Include="..\OdinVault.Storage.Local\OdinVault.Storage.Local.csproj" />
    <ProjectReference Include="..\OdinVault.Storage.GoogleDrive\OdinVault.Storage.GoogleDrive.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Cronos" />
  </ItemGroup>
</Project>
